#!/usr/bin/env bash
# Install and Restart Nginx with the following configurations

sudo apt-get update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
sudo mkdir -p /etc/nginx/html
echo "Hello World!" | sudo /etc/nginx/html/index.html > /dev/null

# Configure nginx to listen on port 80 and return "Hello World!" for GET requests
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        return 200 \"Hello World!\\n\";
    }
}
" | sudo /etc/nginx/sites-available/default > /dev/null

# Restart nginx
sudo service nginx restart
